name: ucasr
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - Cython
  - matplotlib
  - numpy
  - opencv
  - pandas
  - pytorch
  - torchvision
  - torchaudio
  - tqdm
  - pip:
    - librosa==0.9.2
    - pyyaml==6.0
    - scikit-image
    - elasticdeform
    - madmom
    - audiomentations
    - torch_audiomentations
    - wandb
